# Generated by Django 5.0 on 2023-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_options_producto_fechacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fechaCreacion',
        ),
    ]
