# Generated by Django 5.0 on 2023-12-19 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
