# Generated by Django 5.0 on 2023-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plazoReal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
