# Generated by Django 5.0 on 2023-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_fechafin_alter_producto_fechainicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['horaInicio'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='horario',
            field=models.ManyToManyField(to='producto.horarioproducto'),
        ),
    ]
