# Generated by Django 5.0 on 2023-12-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_horarioproducto_name_alter_horarioproducto_horafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='horario',
        ),
        migrations.AddField(
            model_name='producto',
            name='horario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.horarioproducto'),
        ),
    ]
