# Generated by Django 5.0 on 2023-12-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_remove_producto_horario_producto_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasFestivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='plazo',
            field=models.IntegerField(verbose_name='Plazo en días'),
        ),
    ]
