# Generated by Django 5.0 on 2023-12-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_diasfestivos_alter_producto_plazo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiasFestivos',
        ),
    ]
