# Generated by Django 5.0 on 2023-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasFestivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'ordering': ['fecha'],
            },
        ),
    ]
